### ISSUE TITLE
Vite vue-cli

### ISSUE THREAD

**Issue by alexcroox** [loonpwn/nuxt-build-optimisations#22]
For your consideration:

https://github.com/IndexXuan/vue-cli-plugin-vite

Not sure how well it plays with Nuxt but someone has made Vite able to drop into a vue-cli project with no code modifications to speed up dev builds 🤯

**Comment by loonpwn** [comment]
Hey @alexcroox 

Thanks for the link, I did see that package. I have been careful not to do any Vite stuff with this package because I know that Nuxt v3 is going to be bundled with Vite out of the box.

This package is a bridge between that and Nuxt v2, one that someone could throw into any existing project. One of the big speed improvements from Vite is esbuild, which this package uses under the hood. The other optimisations found in Vite are less stable from my experience and aren't worth the effort for existing Nuxt apps.
