### ISSUE TITLE
bug: fails on dev due to svg-loader

### ISSUE THREAD

**Issue by debs-obrien** [loonpwn/nuxt-build-optimisations#4]
**Describe the bug**
Dev server doesn't work

**To Reproduce**
1. Clone repository https://github.com/debs-obrien/debbie.codes
2. install module and run dev
3. Module build failed (from ./node_modules/vue-svg-loader/index.js):  

**Expected behavior**
Generate works but dev doesn't

**Screenshots**
<img width="639" alt="Screenshot 2021-02-11 at 13 10 15" src="https://user-images.githubusercontent.com/13063165/107634862-7dedc600-6c6a-11eb-9228-33cbd5a9de69.png">

**Additional context**
Don't see any improvements in speed, removed node modules and yarn lock. Generation takes same time and dev takes same time but then breaks

**Comment by debs-obrien** [comment]
tested with this: imageFileLoader: false
but still same error

**Comment by loonpwn** [comment]
Thank you, will take a look tomorrow.

**Comment by debs-obrien** [comment]
actually adding  imageFileLoader: false inside features as per docs 🙈 does work

**Comment by AndrewBogdanovTSS** [comment]
@loonpwn is there any way to exclude only specific files and not all images?

**Comment by loonpwn** [comment]
> @loonpwn is there any way to exclude only specific files and not all images?

Hey @AndrewBogdanovTSS 

Would you mind sharing your use case for that behaviour? The replacement of the `url-loader` for `file-loader` should have no side effects on your app (assuming you are using the latest version).

If it is causing some issues then maybe there is something deeper I can look into fixing for you. 

Otherwise as Debbie has said above, you can manually disable this feature using the config.

```js
buildOptimisations: {
 //... 
 features: {
   imageFileLoader: false
 }
}
```

**Comment by AndrewBogdanovTSS** [comment]
@loonpwn I would only like to disable it for one file which is generated from `@nuxtjs/svg-sprite` - icons.svg, other files seems to have no issues with imageFileLoader
